Update ECC memory and add SECDED correctors
micprog/redundancy_cells pull request #14
Opened 2023-07-07 12:57 UTC by micprog

2023-09-19 13:04 UTC, LucaRufer requested changes
The changes look good to me. I focused my review on the ECC encode/correct modules and the corresponding testbench. The only comment I have is a mistake I made in the changelog file.

2023-09-19 13:04 UTC, LucaRufer commented on CHANGELOG.md
> +- Add secded ECC corrector
```suggestion
- Add secded ECC corrector
```

2023-09-19 13:04 UTC, LucaRufer commented on CHANGELOG.md
> +- Update secded testbench to use correctors and fix error injection
```suggestion
- Update secded testbench to use correctors and fix error injection
```

2023-09-19 13:04 UTC, LucaRufer commented on CHANGELOG.md
> +- Add secded ECC corrector
These changes should be listed under "Unreleased" and not under 0.5.1.

2023-12-12 16:08 UTC, yvantor approved these changes
Looks good to me!

2023-12-12 16:12 UTC, merged