Voter Macros
micprog/redundancy_cells pull request #25
Opened 2024-06-10 09:55 UTC by Lynx005F

- Added fault detection only voters
- Added single-line voting macros
   - Macros instantiate voter cells (so they could easily be replaced with technology-specific cells)
   - Macros automatically uniquely name underlying voter cells
   - Macros usable with bender unclude
- Added testbenches for above functionality
- Updated README.md accordingly

2024-06-11 09:34 UTC, micprog requested changes
Minor fixes but LGTM

2024-06-11 09:34 UTC, micprog commented on include/redundancy_cells/voters.svh
> +if (REP == 3) begin \
Can we make `REP` a configurable name?

2024-06-11 09:34 UTC, micprog commented on rtl/TMR_voter_fail.sv
> +// Copyright 2020 ETH Zurich and University of Bologna.
I think you created this in 2024?

2024-06-11 09:40 UTC, micprog commented on include/redundancy_cells/voters.svh
> +if (REP == 3) begin \
It might also make sense to fail (error/fatal) if this new name is <=0 or >3.

2024-06-11 13:17 UTC, 14rynx commented
I fixed the requested changes:
- License
- Explicit replica input to VOTEXX... macros
- Added $fatal for unsupported numbers of replicas

Additionally I managed to not need any error suppression with Enums anymore.

2024-06-14 09:34 UTC, Lynx005F commented on include/redundancy_cells/voters.svh
> +if (REP == 3) begin \
I added REP as first parameter and added a $fatal for unsupported configuraitions.

2024-06-14 09:34 UTC, Lynx005F commented on rtl/TMR_voter_fail.sv
> +// Copyright 2020 ETH Zurich and University of Bologna.
Fixed ;)

2024-06-14 09:36 UTC, Lynx005F commented
I managed to also fix the enum errors that previously needed to be supressed by using an index into an array. Now all enums with >1 bit width work without errors, but Enums with 1 bit only are now unsupported (I think it is fine as one can just use logic instead).

2024-06-18 16:00 UTC, micprog requested changes
I found a few more minor issues, some more critical than others.

2024-06-18 16:00 UTC, micprog commented on README.md
> +include "redundancy_cells/voters.svh"
```suggestion
`include "redundancy_cells/voters.svh"
```

2024-06-18 16:00 UTC, micprog commented on README.md
> +Voters work with enumerated types, but there is no guarante when multiple faults occurr at once that the output is a valid enum entry.
```suggestion
Voters work with enumerated types, but there is no guarantee when multiple faults occur at once that the output is a valid enum entry.
```

2024-06-18 16:00 UTC, micprog commented on include/redundancy_cells/voters.svh
> +if (REP == 3) begin \
```suggestion
if (replicas == 3) begin \
```

2024-06-18 16:00 UTC, micprog commented on include/redundancy_cells/voters.svh
> +if (REP == 3) begin \
```suggestion
if (replicas == 3) begin \
```

2024-06-18 16:00 UTC, micprog commented on include/redundancy_cells/voters.svh
> +if (REP == 3) begin \
```suggestion
if (replicas == 3) begin \
```

2024-06-18 16:00 UTC, micprog commented on test/tb_voter_macros.sv
> +  `VOTE33W(enum_in, enum_out_33w, enum_where_33w, enum_total_33w);
It may be worth extending these sections with the `VOTEX` macros as well.

2024-06-18 16:00 UTC, micprog commented on include/redundancy_cells/voters.svh
> +    assign fault_any = 1'b1; \
I'm not sure if forcing this signal to 1 makes sense if there is no possibility to detect an error. I think it would make more sense to tie to `'0`, as in all likelihood, there was no error, and if this signal is mistakenly used, it will simplify hardware reduction in synthesis. See also above in `VOTE31F` macro.

2024-06-19 05:19 UTC, Lynx005F commented on include/redundancy_cells/voters.svh
> +    assign fault_any = 1'b1; \
I was trying to ensure that there is no case where you set the replicas parameter wrong and the macro works fine, but does not vote the results as expected. I think this is only really an issue in the `VOTEXXF` macro, where a if you would have input and output arrays of size 3 and set replicas = 1 for the macro you would essentially get an unvoted output that looks like it was voted.

But now that I think about it a bit more, the better solution is to specifically only assign the parts of the array that are expected to be used. E.g. in the `VOTEXX(1, ...` case only do ```assign output_signal[0] = input_signal[0];``` That way there is no way extra data makes it through and makes it look like it was voted. 

This then frees up the fault_any to be 0.

2024-06-19 05:30 UTC, Lynx005F commented on include/redundancy_cells/voters.svh
> +    assign fault_any = 1'b1; \
I added the suggested changes and made the degenerate case assignments more rigorous.

2024-06-19 06:48 UTC, Lynx005F commented on test/tb_voter_macros.sv
> +  `VOTE33W(enum_in, enum_out_33w, enum_where_33w, enum_total_33w);
That was a lot of typing... Added `VOTEX` macros in all valid parameterizations.

2024-06-19 06:51 UTC, Lynx005F commented
IMO we can squash all comits without loosing any relevant history

2024-06-19 11:34 UTC, micprog approved these changes
LGTM :+1:

2024-06-19 11:37 UTC, merged